Update __layout.svelte
Context was updated to stuff 
> Error: You are returning "context" from a load function. "context" was renamed to "stuff", please adjust your code accordingly.